theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "net"
device="wlp2s0"
ip=true

[[block]]
block = "temperature"
collapsed = false
interval = 10

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
