[theme]
theme = "bad-wolf"

[icons]
icons = "awesome6"

[[block]]
block = "net"
device="wlp2s0"

[[block]]
block = "temperature"
format_alt = " $icon "
interval = 10


[[block]]
block = "battery"
driver="sysfs"
device="BAT1"
missing_format=""
interval = 10
format = "{percentage}% {time}"
