theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "net"
device="wlp2s0"
ip=true


[[block]]
block = "speedtest"
bytes = true


[[block]]
block = "temperature"
collapsed = false
interval = 10

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"


[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
